# Generated by Django 3.0.3 on 2020-02-25 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('rutaid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ruta', models.CharField(max_length=512)),
            ],
        ),
    ]
